#!/usr/bin/env node
// 설치기 회귀 스위트의 진입점 — 등록(tests 배열)과 실행(샤드 러너)만 둔다.
// 테스트 본문은 scripts/test-init/<영역>.mjs, 공용 픽스처·단언은 scripts/test-init/helpers.mjs.
import os from 'node:os'
import { fileURLToPath } from 'node:url'

import {
  cleanInstallCreatesExpectedFiles,
  pruneAliasesRemovesOnlyRecognizedInjectedValues,
  staleVerifyDeclarationGetsNoticed,
  retiredInitFlagsStayAcceptedForSiblingHarnesses,
  installExcludesSessionWorktrees,
  uninstallUnsetsHarnessGitConfigWhenNothingPreceded,
  nonNodeInstallSkipsPackageJson,
  initPatchesEslintConfigForHarnessFiles,
  initAddsHarnessBackupIgnoreWhenNodeOverrideExists,
  reinstallPreservesProjectOwnedFiles,
  retiredAliasNoticeSurvivesZeroInjection,
  retiredAliasNoticeOmittedWhenNoneExist,
  reinstallMigratesUnchangedSeedSessionStateToConsumerTemplates,
  reinstallPreservesEditedConsumerSessionState,
  reinstallMigratesManagedRootScriptsIntoHarnessBin,
  forceOverwritesProjectOwnedFiles,
  forceRequiresOverwriteConfirmation,
  dryRunDoesNotWriteFiles,
  noBackupRequiresForce,
  externalHarnessWithoutManifestIsPreserved,
  sourceMetadataNormalizesSemverSourceRef,
  baseOnlyUpdateDryRunPassesSourceMetadata,
  harnessBaselineDocUpdateDoesNotTriggerSyncGap,
  harnessNeverRunsProjectQualityScripts,
  updateRecordsAndReplaysChangelogDelta,
  reinstallPreservesLocallyEditedManagedHarnessFile,
  initExcludesHarnessFromEveryLintSurface,
  harnessCheckReportsManagedFileDrift,
  managedDriftIgnoresMarkerHybridFiles,
  resyncManagedRestoresHarnessFilesButNotProjectOwned,
  consumerGitignoreCoversAllGeneratedSessionArtifacts,
  forceConfirmOverwritesLocallyEditedManagedHarnessFileWithBackup,
  forceAloneStopsWhenManagedHarnessFileWasLocallyEdited,
  newInstallWritesMarkerAndRegionSha,
  markerMergePreservesConsumerAreaAndUpdatesManagedBlock,
  markerMergeRestoresTamperedManagedBlockWithSidecar,
  autoMigrateUnmodifiedLegacyFileToMarkerVersion,
  prependHarnessBlockOntoModifiedLegacyFileWithoutMarker,
  markerMergeIsIdempotent,
  consumerInstallExcludesSeedOnlyDocs,
  reinstallRemovesPreexistingSeedOnlyDocWhenUnmodified,
  reinstallPreservesModifiedSeedOnlyDoc,
  consumerInstallExcludesSessionHistoryLogs,
  updateRemovesSeedDistributedHistoryLogWhenUnmodified,
  updatePreservesConsumerOwnedHistoryLog,
  updateRemovesRetiredManagedCommandDoc,
  backupSkipsWhatGitCanRestoreAndRotatesSets,
  installDeclaresCmdLineEndingsSoGitStopsWarning,
  twoStageUpdateRecordsTheRealStartVersion,
  installOutputEndsWithReportPrompt,
  linkedAddDeclaresWithoutLocalFolder,
  linkedAddWritesProfileAndLocalSettings,
  updateRefreshesStaleHarnessModeNotes,
  bootstrapModeAlwaysRelaxesSyncCandidates,
  firstAlphabeticalUnstagedChangeKeepsItsName,
  crlfCheckoutDoesNotFreezeManagedFiles,
  installerWritesDeterministicEol,
  commitTemplateIsProjectOwnedAndCustomizable,
  installWarnsWhenSharedOutputsAreGitIgnored,
  driftSkipsProjectOwnedListedEntries,
  updateOutputSkipsStaticCommandGuide,
  chainedUpdateKeepsOriginalFromForChangelogAndReport,
  seedModeTargetKeepsSeedOnlyDocs,
  profileProjectSourcesDoNotTriggerInstallSyncGap,
  registeredServiceRuleDocKeepsASlotInRelevantPolicies,
  guideSyncPolicyKeepsBundledGuideLinked,
  checkFlagsAnUnlinkedProjectEntrypointUntilItIsLinked,
  installNeverShipsTheSeedsPersonalLocalFiles,
  installedQueueSnoozesCharterQuestionsAndProfileStaysThin,
  commitAdvisoryIgnoresDocsAndMetaFilesInMappedAreas,
  installTellsProjectOwnFilesApartFromPriorHarness,
} from './test-init/install.mjs'
import {
  freshInstallAutoActivatesGitHooks,
  sessionStartAdapterWarnsWhenHooksMissing,
  sessionStartHookAutoEnablesGitHooks,
  hooksInstallFailsClearlyOutsideGit,
  uninstallRestoresPreviousHooksPathForHuskyStyleProjects,
  gitHooksRunWithoutNpm,
  previousHookChainStopsOnRecursion,
  sessionOnlyCommitSkipsHeavyCheck,
  existingClaudeSettingsGetsHarnessHooksMerged,
  hooksInstallKeepsExistingGitHooksRunning,
  legacyInstallWithDefaultDirMarkerMigratesToWrappers,
  parkedTeamHooksRunFromLinkedWorktree,
  reinstallPrefersNewestTeamHookAndUninstallRestoresIt,
  wrapperReentryFromHuskyRunsParkedOriginalOnly,
  parkedSymlinkHookKeepsWorking,
  globalHooksPathIsOverriddenLocallyNotUnset,
  globalHooksPathOverrideWorksFromLinkedWorktree,
  crossHookCallRunsTheRealHook,
  blockedNewManagedScriptSaysItWasJustInstalled,
  promptChannelShowsPrerequisitesOncePerSession,
  noChannelCallsAnUnreadableHookStateOff,
  pullReportsTheSameUnmetPrerequisites,
  sessionStartTablesUnmetPrerequisites,
  hookOffNoticeTellsAboutTheNextSession,
  hooksStatusNoticeSuitsTheEnvironment,
  sessionStartJudgesHookMigrationByStateNotExitCode,
  wrapperCoversAllClientHookNames,
  hooksSurviveCheckoutToBranchWithoutHarness,
  sessionStartHookInjectsLinkedProjectPointers,
  bodyHooksDeclareScope,
  hookCoexistenceDocCoversOwnHookDirPattern,
  hooksInstallWarnsWhenStoredChainIsReplaced,
  dangerousHookAllowsWriterHeredocMentions,
  defaultAllowListCoversContextAndSync,
  dangerousHookAllowsOnlyCommittedUnmodifiedScripts,
  installStopsOnForeignHookConflictUntilResolved,
  seedCommitStageDefersRegressionsToPush,
  commitStageEnvIsNoopForConsumers,
  prePushPassesBufferedStdinToPreviousHook,
  sessionStartHookSnoozesQueueRowsUntilReviewDate,
} from './test-init/hooks.mjs'
import {
  installOutputUsesConditionalNvmAndGitGuidance,
  launcherRunsHarnessWithoutNpm,
  lowProjectNvmrcInstallsInDualRuntimeMode,
  lowProjectNvmrcWithoutNvmStopsInit,
  projectNodeFlagWritesNvmrcWithUserConfirmation,
  missingNvmrcWithLowNodeSignalRequiresInterview,
  enginesFloorDoesNotForceProjectNodeInterview,
  dualNodeHelpersAreArgSafeUnderSetU,
  dualNodeDoesNotExportDotWhenNodeIsShellFunction,
  backendWithoutNvmrcSkipsProjectNodeInterview,
  dualNodeShSwitchesHarnessNodeWhenActiveNodeIsLow,
  existingProjectNvmrcIsPreserved,
  launcherSubcommandsWithoutRegressionsRunClean,
} from './test-init/runtime.mjs'
import {
  scanReportSuggestsBridgeCandidates,
  stackResetDoesNotResurrectDeletedProfileKeys,
  stackApplyMaterializesPresetAsLocalRules,
  stackApplySupportsExternalPresetPath,
  harnessOutdatedDetectsBaseAndStackUpdates,
  stackApplySupportsExternalPresetGit,
  stackApplySupportsRulesOnlyPreset,
  templateApplyCreatesBridgeWithoutReplacingActiveStack,
  templateApplyCreatesProjectNvmrcWhenMissing,
  templateApplyStopsWhenRequiredStackDoesNotMatch,
  scanReportSuggestsStylePresetsWhenStyleSourceMissing,
  guardDerivesAppliedStackFromTrackedSnapshotWhenMarkerMissing,
  guardFailsWhenActiveStackHasNoTrackedSnapshot,
  stackAbsenceIsQuietNormalState,
  stackAuthoringGuideStaysReachableAfterExclusion,
  stackAuthoringGuideSpeaksEveryRuntime,
  templatePackageMergeAddsWithoutReplacingTheProjectFile,
  templateAuthoringGuideStaysReachableAndCarriesItsContract,
  templateMinStackVersionBlocksLowAndUnjudgeable,
  bodyDoesNotTrackForeignStacksOrTemplates,
  stackAndTemplateRegistriesLiveUnderTheirOwnGroups,
  updateSkipsStackForBaseOnlyFlags,
} from './test-init/stack.mjs'
import {
  scanReportDraftsStyleRulesFromConfigFiles,
  isIgnorableCodePathClassifiesExamplesAndCiPaths,
  consumerDocLinkCheckIgnoresCiExamplePaths,
  consumerDocLinkCheckHandlesAbsentSeedOnlyDoc,
  freshInstallHasNoRegistryOrphans,
  criticalPathGhostDeclarationsGetNoticed,
  criticalPathCellWithMultipleBacktickPathsMatchesEach,
  orphanNoticePointsToLocalRegistryExit,
  localPolicyRegistryIsMergedAndProjectOwned,
  preservedForeignRegistryIsGuidedAndReadopted,
  freshCriticalPathTemplateStartsEmpty,
  scanTreatsEveryDeclaredSourceAsRuleDoc,
  scanValidatesDeclaredProjectSources,
  installReportsExistingAiRuleDocuments,
  scanReportsHeadingOnlyAiRuleDocuments,
  scanReportsIgnoredAiRuleCandidates,
  scanIgnoresArchivedRuleCopies,
  scanPrefersTrackedAiRuleForRegistrationExample,
  historyLogPathClassifiesDecisionLogFamily,
  consumerDocLinkCheckSkipsDecisionLogHistoryPaths,
  consumerDocLinkCheckStillFlagsLiveDocDeadPaths,
  docLinkCheckPrintsSingleLineWhenClean,
  codingConventionsShipsAsProjectOwnedRuleDoc,
  codingConventionsBecomeAlwaysReadOnceFilled,
  skillRegistryPointsAtRealFilesAndCommands,
  scanTreatsLocallyRegisteredDocsAsHandled,
  docLinkTreatsDeletedProjectOwnedDocsAsOptional,
  docLinkKeepsRequiredProjectOwnedDocsMandatory,
  approvedRegistryListingsStayConsistent,
  localDocumentRegistryGivesProjectOwnedRegistrationPoint,
} from './test-init/scan.mjs'
import {
  workflowWorkstreamChangeDoesNotTriggerCommitPushHookPolicy,
  guardCacheHitSkipsRevalidationOnSameTree,
  guardFullCacheSatisfiesFastRequest,
  guardNoCacheForcesRevalidation,
  guardCacheMissAfterTreeChange,
  buildContextMergesProfileAlwaysSources,
  guardModeDefaultsToSummaryImpactOutput,
  guardSummaryStillDetailsMustActSyncCandidates,
  guardEscalatesSyncCandidatesOnReversalCommit,
  guardDoesNotEscalateProseWithoutBannerEmoji,
  guardNoticesLogOnlyReversalCommit,
  guardLintsOverrideEntryRebuttalField,
  guardNudgesDecisionLogArchiveWhenOversizedAndTouched,
  promotionReminderAsksExecutableGuardBranch,
  contextSelectsRulePromotionForEntrypointMigrationRequest,
  contextClassifiesPlainKoreanDevelopmentRequest,
  guardFlagsInvalidHarnessModeInsteadOfSilentlyDowngrading,
} from './test-init/guard.mjs'
import {
  reportInstallHelpWritesNothing,
  reportInstallFailsOpenToFileWithoutToken,
  historyBoardHeadlinesTheLatestRelease,
  pendingReportMarkerRemindsUntilReported,
  releaseNoticeBuildsPayloadFromLatestChangelogSection,
  ciReleaseNoticeYamlParsesAndDelegates,
  newProjectChecklistShipsWithPointers,
  issueAdapterExampleShipsAsSwitchContract,
} from './test-init/release.mjs'
import {
  hooksInstallHydratesSpecBodiesForFreshClone,
  hooksInstallStaysQuietWithoutSpecLink,
  specSyncFetchRecordsLockAndDetectsChanges,
  buildContextInjectsRelatedSpecs,
  guardShowsSpecAdvisoryForMappedCodeChange,
  specFetchCacheOnlyDoesNotMoveTeamBaseline,
  specFetchAtLockRehydratesCacheAtBaseline,
  specSettleAdvancesOnlyMyScopedDocs,
  specLinkConsistencyCheckFlagsBrokenDeclarations,
  broadcastSpeaksMixedAudienceLanguage,
  broadcastDistinguishesJudgedDocsFromUnmapped,
  broadcastWithoutCheckRecordAsksForFetchFirst,
  specStatusSeparatesAxesAndFoldsDetectedCount,
  specStatusLabelsLinkedScreenWithItsDocMapping,
  ciBackstopExampleDelegatesToBroadcast,
  ciBackstopLeaderChecklistCoversLiveSetup,
  specLinkAdapterRoutesSecondSourceToAddProcedure,
  specSyncPublicSurfaceStaysLocked,
  specAtLockRestoresExactMixedBaselineSet,
  specMoveBaselineSourceScopeKeepsOtherSourcesIntact,
  specV1LockReadPathsArePureAndMutatingCommandsPromote,
  specSourceValidationInvalidatesWholeState,
  specFetchReclonesWhenRepoUrlChanges,
  specSelectorChangeIsFlaggedByConsistency,
  specUninstallRemovesSpecScripts,
  specStatusDoesNotClaimSyncWhenCacheMissing,
  specSettleRefusesPathCollisionsAcrossSources,
  specReplacedScreenSettlesOldAndNewTogether,
  specSettleFailsClosedWithoutTheBaselineCache,
  specSettleReadsBaselineScreensFromGitObjectsWithoutCheckout,
  specDeletedScreenUnitSettlesTogetherFromBaselineIndex,
  specSettleRefusalLeavesLockUntouchedRegardlessOfV1OrArgOrder,
  specExemptionRowsGetTheSameSourceChecksAsMappings,
  specSettleRefusesAllWhenOneRequestedDocIsMissing,
  specQualifiedRefsSurviveStrictCheckAndScopedSettle,
  specRefsQualifiedBySourceSettleTheRightBaseline,
  specMappingCoverageIsEnforcedForNewFilesInMappedAreas,
  specMapRowsSurviveNotesThatMentionTheHeaderWords,
  specNoticeScopesUnrelatedServicesToOneFoldedLine,
  specContextBudgetGrowsWithSourceCount,
  specMappingCoverageRespectsExemptionsAndScope,
  specCacheHydratesAutomaticallyAndFailsHarmlessly,
  specHydrationDetectsPerDocumentDrift,
  specContextSurfacesChangedAndNewPlanningDocs,
  specSettleRecordsReviewedSnapshotNotLatest,
  specSettleNeverMovesBaselineBackwards,
  specStaleDeleteSnapshotDoesNotRemoveLiveDoc,
  specColdCacheCheckDoesNotLeakLatestIntoBaseline,
  specSettleRefusesNewCollisionAcrossSources,
  specFailedFreshnessIsNotReplayedAsSuccess,
  specSettleRefusesUnreviewedDocuments,
  specHydrationRefusesSymlinkEscape,
  specSettleRefusesForgedSnapshotBody,
  specSettleRefusesForgedDeletion,
  specSettleRefusesSnapshotFromAnotherRepo,
  specStorageRootSymlinkIsRefused,
  specContextRefusesSymlinkedSpecBody,
  specCorruptedStateFilesFailClosed,
  specLatestDirectoryIsExactSnapshotSet,
  specCorruptedLockSchemaFailsClosed,
  specSettleRefusesRollbackToRealPastCommit,
  specSettleRefusesSnapshotCommitMismatch,
  specSettleRefusesSwappedCacheOrigin,
  specSettleRefusesWhenDeclarationDrifted,
  specLockOnlyAndGlobalFailureAreSurfaced,
  specScreenLinkIntegrityIsEnforced,
  specScreenLinkSettlesAtomically,
  specSettleRefusesRevivingDeletedDocFromPast,
  specUnlinkedScreenIsSurfacedRegardlessOfInclude,
  specGuardNoticesMissingHookInstall,
  specLatestPruneKeepsRecordAndFilesInSync,
  specLargeScreenFileEntersBaseline,
  specStatusGuidesMappingAtStart,
  specStatusFlagsDocScreenBaselineMismatch,
  specFreshnessFailureIsNotMaskedByPastSuccess,
  specContextRefusesUnverifiedBodies,
  specContextSurfacesOpaquelyNamedDocs,
  specMappingCoverageDetectsModifiedExistingFiles,
} from './test-init/spec.mjs'

const __filename = fileURLToPath(import.meta.url)

const tests = [
  sessionStartHookSnoozesQueueRowsUntilReviewDate,
  localDocumentRegistryGivesProjectOwnedRegistrationPoint,
  updateSkipsStackForBaseOnlyFlags,
  cleanInstallCreatesExpectedFiles,
  pruneAliasesRemovesOnlyRecognizedInjectedValues,
  staleVerifyDeclarationGetsNoticed,
  retiredInitFlagsStayAcceptedForSiblingHarnesses,
  installExcludesSessionWorktrees,
  freshInstallAutoActivatesGitHooks,
  sessionStartAdapterWarnsWhenHooksMissing,
  sessionStartHookAutoEnablesGitHooks,
  installOutputUsesConditionalNvmAndGitGuidance,
  hooksInstallFailsClearlyOutsideGit,
  uninstallUnsetsHarnessGitConfigWhenNothingPreceded,
  uninstallRestoresPreviousHooksPathForHuskyStyleProjects,
  nonNodeInstallSkipsPackageJson,
  launcherRunsHarnessWithoutNpm,
  gitHooksRunWithoutNpm,
  previousHookChainStopsOnRecursion,
  sessionOnlyCommitSkipsHeavyCheck,
  initPatchesEslintConfigForHarnessFiles,
  initAddsHarnessBackupIgnoreWhenNodeOverrideExists,
  reinstallPreservesProjectOwnedFiles,
  retiredAliasNoticeSurvivesZeroInjection,
  retiredAliasNoticeOmittedWhenNoneExist,
  reinstallMigratesUnchangedSeedSessionStateToConsumerTemplates,
  reinstallPreservesEditedConsumerSessionState,
  reinstallMigratesManagedRootScriptsIntoHarnessBin,
  forceOverwritesProjectOwnedFiles,
  forceRequiresOverwriteConfirmation,
  dryRunDoesNotWriteFiles,
  noBackupRequiresForce,
  lowProjectNvmrcInstallsInDualRuntimeMode,
  lowProjectNvmrcWithoutNvmStopsInit,
  projectNodeFlagWritesNvmrcWithUserConfirmation,
  missingNvmrcWithLowNodeSignalRequiresInterview,
  enginesFloorDoesNotForceProjectNodeInterview,
  backendWithoutNvmrcSkipsProjectNodeInterview,
  dualNodeShSwitchesHarnessNodeWhenActiveNodeIsLow,
  dualNodeHelpersAreArgSafeUnderSetU,
  dualNodeDoesNotExportDotWhenNodeIsShellFunction,
  existingProjectNvmrcIsPreserved,
  externalHarnessWithoutManifestIsPreserved,
  scanReportSuggestsBridgeCandidates,
  stackResetDoesNotResurrectDeletedProfileKeys,
  stackApplyMaterializesPresetAsLocalRules,
  stackApplySupportsExternalPresetPath,
  harnessOutdatedDetectsBaseAndStackUpdates,
  sourceMetadataNormalizesSemverSourceRef,
  baseOnlyUpdateDryRunPassesSourceMetadata,
  stackApplySupportsExternalPresetGit,
  stackApplySupportsRulesOnlyPreset,
  templateApplyCreatesBridgeWithoutReplacingActiveStack,
  templateApplyCreatesProjectNvmrcWhenMissing,
  templateApplyStopsWhenRequiredStackDoesNotMatch,
  scanReportSuggestsStylePresetsWhenStyleSourceMissing,
  scanReportDraftsStyleRulesFromConfigFiles,
  workflowWorkstreamChangeDoesNotTriggerCommitPushHookPolicy,
  harnessBaselineDocUpdateDoesNotTriggerSyncGap,
  guardDerivesAppliedStackFromTrackedSnapshotWhenMarkerMissing,
  harnessNeverRunsProjectQualityScripts,
  guardFailsWhenActiveStackHasNoTrackedSnapshot,
  updateRecordsAndReplaysChangelogDelta,
  existingClaudeSettingsGetsHarnessHooksMerged,
  reinstallPreservesLocallyEditedManagedHarnessFile,
  initExcludesHarnessFromEveryLintSurface,
  harnessCheckReportsManagedFileDrift,
  managedDriftIgnoresMarkerHybridFiles,
  resyncManagedRestoresHarnessFilesButNotProjectOwned,
  consumerGitignoreCoversAllGeneratedSessionArtifacts,
  forceConfirmOverwritesLocallyEditedManagedHarnessFileWithBackup,
  forceAloneStopsWhenManagedHarnessFileWasLocallyEdited,
  newInstallWritesMarkerAndRegionSha,
  markerMergePreservesConsumerAreaAndUpdatesManagedBlock,
  markerMergeRestoresTamperedManagedBlockWithSidecar,
  autoMigrateUnmodifiedLegacyFileToMarkerVersion,
  prependHarnessBlockOntoModifiedLegacyFileWithoutMarker,
  markerMergeIsIdempotent,
  isIgnorableCodePathClassifiesExamplesAndCiPaths,
  consumerDocLinkCheckIgnoresCiExamplePaths,
  consumerInstallExcludesSeedOnlyDocs,
  consumerInstallExcludesSessionHistoryLogs,
  updateRemovesSeedDistributedHistoryLogWhenUnmodified,
  updatePreservesConsumerOwnedHistoryLog,
  consumerDocLinkCheckHandlesAbsentSeedOnlyDoc,
  reinstallRemovesPreexistingSeedOnlyDocWhenUnmodified,
  reinstallPreservesModifiedSeedOnlyDoc,
  criticalPathGhostDeclarationsGetNoticed,
  criticalPathCellWithMultipleBacktickPathsMatchesEach,
  orphanNoticePointsToLocalRegistryExit,
  hooksInstallWarnsWhenStoredChainIsReplaced,
  sessionStartHookInjectsLinkedProjectPointers,
  bodyHooksDeclareScope,
  hookCoexistenceDocCoversOwnHookDirPattern,
  linkedAddWritesProfileAndLocalSettings,
  linkedAddDeclaresWithoutLocalFolder,
  installOutputEndsWithReportPrompt,
  hooksInstallKeepsExistingGitHooksRunning,
  hooksSurviveCheckoutToBranchWithoutHarness,
  defaultAllowListCoversContextAndSync,
  dangerousHookAllowsOnlyCommittedUnmodifiedScripts,
  installStopsOnForeignHookConflictUntilResolved,
  installWarnsWhenSharedOutputsAreGitIgnored,
  legacyInstallWithDefaultDirMarkerMigratesToWrappers,
  parkedTeamHooksRunFromLinkedWorktree,
  reinstallPrefersNewestTeamHookAndUninstallRestoresIt,
  wrapperReentryFromHuskyRunsParkedOriginalOnly,
  parkedSymlinkHookKeepsWorking,
  globalHooksPathIsOverriddenLocallyNotUnset,
  wrapperCoversAllClientHookNames,
  hooksStatusNoticeSuitsTheEnvironment,
  localPolicyRegistryIsMergedAndProjectOwned,
  installDeclaresCmdLineEndingsSoGitStopsWarning,
  twoStageUpdateRecordsTheRealStartVersion,
  preservedForeignRegistryIsGuidedAndReadopted,
  sessionStartJudgesHookMigrationByStateNotExitCode,
  globalHooksPathOverrideWorksFromLinkedWorktree,
  crossHookCallRunsTheRealHook,
  reportInstallHelpWritesNothing,
  updateRefreshesStaleHarnessModeNotes,
  bootstrapModeAlwaysRelaxesSyncCandidates,
  firstAlphabeticalUnstagedChangeKeepsItsName,
  crlfCheckoutDoesNotFreezeManagedFiles,
  installerWritesDeterministicEol,
  commitTemplateIsProjectOwnedAndCustomizable,
  dangerousHookAllowsWriterHeredocMentions,
  stackAbsenceIsQuietNormalState,
  driftSkipsProjectOwnedListedEntries,
  freshCriticalPathTemplateStartsEmpty,
  reportInstallFailsOpenToFileWithoutToken,
  historyBoardHeadlinesTheLatestRelease,
  hookOffNoticeTellsAboutTheNextSession,
  sessionStartTablesUnmetPrerequisites,
  pullReportsTheSameUnmetPrerequisites,
  noChannelCallsAnUnreadableHookStateOff,
  promptChannelShowsPrerequisitesOncePerSession,
  backupSkipsWhatGitCanRestoreAndRotatesSets,
  blockedNewManagedScriptSaysItWasJustInstalled,
  pendingReportMarkerRemindsUntilReported,
  updateOutputSkipsStaticCommandGuide,
  chainedUpdateKeepsOriginalFromForChangelogAndReport,
  seedModeTargetKeepsSeedOnlyDocs,
  updateRemovesRetiredManagedCommandDoc,
  freshInstallHasNoRegistryOrphans,
  guardCacheHitSkipsRevalidationOnSameTree,
  guardFullCacheSatisfiesFastRequest,
  seedCommitStageDefersRegressionsToPush,
  commitStageEnvIsNoopForConsumers,
  guardNoCacheForcesRevalidation,
  guardCacheMissAfterTreeChange,
  buildContextMergesProfileAlwaysSources,
  scanValidatesDeclaredProjectSources,
  scanTreatsEveryDeclaredSourceAsRuleDoc,
  installReportsExistingAiRuleDocuments,
  scanReportsHeadingOnlyAiRuleDocuments,
  scanReportsIgnoredAiRuleCandidates,
  scanPrefersTrackedAiRuleForRegistrationExample,
  scanIgnoresArchivedRuleCopies,
  profileProjectSourcesDoNotTriggerInstallSyncGap,
  historyLogPathClassifiesDecisionLogFamily,
  consumerDocLinkCheckSkipsDecisionLogHistoryPaths,
  consumerDocLinkCheckStillFlagsLiveDocDeadPaths,
  docLinkCheckPrintsSingleLineWhenClean,
  guardModeDefaultsToSummaryImpactOutput,
  guardSummaryStillDetailsMustActSyncCandidates,
  guardEscalatesSyncCandidatesOnReversalCommit,
  guardDoesNotEscalateProseWithoutBannerEmoji,
  guardNoticesLogOnlyReversalCommit,
  guardLintsOverrideEntryRebuttalField,
  guardNudgesDecisionLogArchiveWhenOversizedAndTouched,
  promotionReminderAsksExecutableGuardBranch,
  hooksInstallHydratesSpecBodiesForFreshClone,
  hooksInstallStaysQuietWithoutSpecLink,
  specSyncFetchRecordsLockAndDetectsChanges,
  broadcastSpeaksMixedAudienceLanguage,
  broadcastDistinguishesJudgedDocsFromUnmapped,
  broadcastWithoutCheckRecordAsksForFetchFirst,
  specStatusSeparatesAxesAndFoldsDetectedCount,
  specStatusLabelsLinkedScreenWithItsDocMapping,
  ciBackstopExampleDelegatesToBroadcast,
  ciBackstopLeaderChecklistCoversLiveSetup,
  specLinkAdapterRoutesSecondSourceToAddProcedure,
  releaseNoticeBuildsPayloadFromLatestChangelogSection,
  ciReleaseNoticeYamlParsesAndDelegates,
  newProjectChecklistShipsWithPointers,
  issueAdapterExampleShipsAsSwitchContract,
  specSyncPublicSurfaceStaysLocked,
  guideSyncPolicyKeepsBundledGuideLinked,
  buildContextInjectsRelatedSpecs,
  contextClassifiesPlainKoreanDevelopmentRequest,
  contextSelectsRulePromotionForEntrypointMigrationRequest,
  codingConventionsShipsAsProjectOwnedRuleDoc,
  codingConventionsBecomeAlwaysReadOnceFilled,
  registeredServiceRuleDocKeepsASlotInRelevantPolicies,
  guardShowsSpecAdvisoryForMappedCodeChange,
  specFetchCacheOnlyDoesNotMoveTeamBaseline,
  specFetchAtLockRehydratesCacheAtBaseline,
  specSettleAdvancesOnlyMyScopedDocs,
  specLinkConsistencyCheckFlagsBrokenDeclarations,
  specAtLockRestoresExactMixedBaselineSet,
  specMoveBaselineSourceScopeKeepsOtherSourcesIntact,
  specV1LockReadPathsArePureAndMutatingCommandsPromote,
  prePushPassesBufferedStdinToPreviousHook,
  specSourceValidationInvalidatesWholeState,
  specFetchReclonesWhenRepoUrlChanges,
  specSelectorChangeIsFlaggedByConsistency,
  specUninstallRemovesSpecScripts,
  specStatusDoesNotClaimSyncWhenCacheMissing,
  specSettleRefusesPathCollisionsAcrossSources,
  specRefsQualifiedBySourceSettleTheRightBaseline,
  specQualifiedRefsSurviveStrictCheckAndScopedSettle,
  specExemptionRowsGetTheSameSourceChecksAsMappings,
  specSettleRefusesAllWhenOneRequestedDocIsMissing,
  specSettleRefusalLeavesLockUntouchedRegardlessOfV1OrArgOrder,
  specDeletedScreenUnitSettlesTogetherFromBaselineIndex,
  specReplacedScreenSettlesOldAndNewTogether,
  specSettleFailsClosedWithoutTheBaselineCache,
  specSettleReadsBaselineScreensFromGitObjectsWithoutCheckout,
  specMappingCoverageIsEnforcedForNewFilesInMappedAreas,
  specMappingCoverageRespectsExemptionsAndScope,
  specMapRowsSurviveNotesThatMentionTheHeaderWords,
  skillRegistryPointsAtRealFilesAndCommands,
  launcherSubcommandsWithoutRegressionsRunClean,
  stackAuthoringGuideStaysReachableAfterExclusion,
  stackAuthoringGuideSpeaksEveryRuntime,
  stackAndTemplateRegistriesLiveUnderTheirOwnGroups,
  bodyDoesNotTrackForeignStacksOrTemplates,
  installNeverShipsTheSeedsPersonalLocalFiles,
  templateMinStackVersionBlocksLowAndUnjudgeable,
  templatePackageMergeAddsWithoutReplacingTheProjectFile,
  checkFlagsAnUnlinkedProjectEntrypointUntilItIsLinked,
  templateAuthoringGuideStaysReachableAndCarriesItsContract,
  installedQueueSnoozesCharterQuestionsAndProfileStaysThin,
  specNoticeScopesUnrelatedServicesToOneFoldedLine,
  commitAdvisoryIgnoresDocsAndMetaFilesInMappedAreas,
  specContextBudgetGrowsWithSourceCount,
  installTellsProjectOwnFilesApartFromPriorHarness,
  scanTreatsLocallyRegisteredDocsAsHandled,
  specCacheHydratesAutomaticallyAndFailsHarmlessly,
  specHydrationDetectsPerDocumentDrift,
  specContextSurfacesChangedAndNewPlanningDocs,
  specSettleRecordsReviewedSnapshotNotLatest,
  specSettleNeverMovesBaselineBackwards,
  specStaleDeleteSnapshotDoesNotRemoveLiveDoc,
  specColdCacheCheckDoesNotLeakLatestIntoBaseline,
  specSettleRefusesNewCollisionAcrossSources,
  specFailedFreshnessIsNotReplayedAsSuccess,
  specSettleRefusesUnreviewedDocuments,
  specHydrationRefusesSymlinkEscape,
  specCorruptedLockSchemaFailsClosed,
  specSettleRefusesRollbackToRealPastCommit,
  specSettleRefusesSnapshotCommitMismatch,
  specSettleRefusesSwappedCacheOrigin,
  specSettleRefusesWhenDeclarationDrifted,
  specLockOnlyAndGlobalFailureAreSurfaced,
  specLargeScreenFileEntersBaseline,
  specStatusGuidesMappingAtStart,
  specStatusFlagsDocScreenBaselineMismatch,
  specLatestPruneKeepsRecordAndFilesInSync,
  specSettleRefusesRevivingDeletedDocFromPast,
  specUnlinkedScreenIsSurfacedRegardlessOfInclude,
  specGuardNoticesMissingHookInstall,
  specScreenLinkIntegrityIsEnforced,
  specScreenLinkSettlesAtomically,
  specSettleRefusesForgedSnapshotBody,
  specSettleRefusesForgedDeletion,
  specSettleRefusesSnapshotFromAnotherRepo,
  specStorageRootSymlinkIsRefused,
  specContextRefusesSymlinkedSpecBody,
  specCorruptedStateFilesFailClosed,
  specLatestDirectoryIsExactSnapshotSet,
  specFreshnessFailureIsNotMaskedByPastSuccess,
  specContextRefusesUnverifiedBodies,
  specContextSurfacesOpaquelyNamedDocs,
  docLinkTreatsDeletedProjectOwnedDocsAsOptional,
  docLinkKeepsRequiredProjectOwnedDocsMandatory,
  specMappingCoverageDetectsModifiedExistingFiles,
  guardFlagsInvalidHarnessModeInsteadOfSilentlyDowngrading,
  approvedRegistryListingsStayConsistent,
]

// 인자를 주면 이름에 그 문자열을 포함한 테스트만 돌린다(개발 반복용). 게이트는 무인자 전체 실행.
//
// 병렬 실행(0.2.134): 테스트는 각자 임시 디렉터리를 만들어 서로 독립이므로,
// 무인자 전체 실행은 샤드 자식 프로세스로 나눠 병렬로 돈다(10코어에서 직렬로 돌던
// 3~5분이 릴리스마다 4~5회 반복되던 것이 원인 — 2026-08-31 실측). 이름 필터·--sequential·
// HARNESS_TESTS_SEQUENTIAL=1 은 종전처럼 직렬. 샤드는 인덱스 라운드로빈으로 나눠
// 무거운 spec 군집이 한 샤드에 몰리지 않게 한다.
const rawArgs = process.argv.slice(2)
const shardArg = rawArgs.find((arg) => arg.startsWith('--shard='))
const sequential = rawArgs.includes('--sequential') || process.env.HARNESS_TESTS_SEQUENTIAL === '1'
const nameFilter = rawArgs.find((arg) => !arg.startsWith('--'))

function runSerial(list, header) {
  console.log(header)
  for (const test of list) {
    test()
    console.log(`  OK ${test.name}`)
  }
}

if (shardArg) {
  const match = shardArg.match(/^--shard=(\d+)\/(\d+)$/)
  if (!match) {
    console.error(`잘못된 샤드 지정: ${shardArg} (예: --shard=0/8)`)
    process.exit(1)
  }
  const shardIndex = Number(match[1])
  const shardCount = Number(match[2])
  const mine = tests.filter((_, index) => index % shardCount === shardIndex)
  runSerial(mine, `Init smoke tests (shard ${shardIndex + 1}/${shardCount}, ${mine.length}/${tests.length})`)
} else if (nameFilter) {
  const selected = tests.filter((test) => test.name.includes(nameFilter))
  runSerial(selected, `Init smoke tests (filter: ${nameFilter}, ${selected.length}/${tests.length})`)
} else if (sequential) {
  runSerial(tests, 'Init smoke tests (sequential)')
} else {
  const { spawn } = await import('node:child_process')
  const shardCount = Math.max(2, Math.min(8, os.cpus().length - 2))
  const startedAt = Date.now()
  console.log(`Init smoke tests (${tests.length} tests, ${shardCount} shards)`)

  const children = Array.from({ length: shardCount }, (_, index) => new Promise((resolve) => {
    const child = spawn(process.execPath, [__filename, `--shard=${index}/${shardCount}`], {
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    let output = ''
    child.stdout.on('data', (chunk) => { output += chunk })
    child.stderr.on('data', (chunk) => { output += chunk })
    child.on('close', (code) => resolve({ index, code, output }))
  }))

  const results = await Promise.all(children)
  let passed = 0
  for (const result of results) {
    passed += (result.output.match(/^  OK /gm) ?? []).length
  }
  const failed = results.filter((result) => result.code !== 0)
  for (const result of failed) {
    console.error(`--- shard ${result.index + 1}/${shardCount} 실패 ---`)
    console.error(result.output.split('\n').slice(-25).join('\n'))
  }
  const seconds = ((Date.now() - startedAt) / 1000).toFixed(0)
  console.log(`  OK ${passed}/${tests.length} tests (${shardCount} shards, ${seconds}s)`)
  if (failed.length > 0 || passed !== tests.length) {
    console.error(`실패 샤드 ${failed.length}개 / 통과 ${passed}/${tests.length}`)
    process.exit(1)
  }
}
